### ISSUE TITLE
How to finally convert all images to webp?

### ISSUE THREAD

**Issue by smfaramarzirad** [jw-12138/vite-plugin-vsharp#13]
How to finally convert all images to webp?

**Comment by jw-12138** [comment]
@smfaramarzirad hey there!

currently, this plugin doesn't support for converting images to specific formats, ~~but i have to say it is actully a good idea!~~

~~I'll let you know when the feature is ready!~~

**Comment by jw-12138** [comment]
my bad, 😥.

initially i thought it's just a simple task, but after some digging i found that adding this feature meaning we have to change the in-code image url since the extension has changed.

my suggestion here is to have the original images into the desired format, then use this plugin for compression.
