### ISSUE TITLE
[Bug] animated gifs have their animation removed

### ISSUE THREAD

**Issue by FatehAK** [jw-12138/vite-plugin-vsharp#8]
![thumbsup](https://user-images.githubusercontent.com/34565559/206894610-a2a2b628-575b-4b8f-b419-659d0787c8be.gif)

When vsharp processes the above file the animation is removed. I think its related to https://github.com/lovell/sharp/issues/3258 and may require a config change in the plugin.

**Comment by jw-12138** [comment]
fixed it in version 1.3.0, thanks for pointing this out!

https://github.com/jw-12138/vite-plugin-vsharp/commit/e3cd4b8af19ba4ea7196998e0460c39e425df219

**Comment by FatehAK** [comment]
Great! will check it out

**Comment by FatehAK** [comment]
Just checked seems like the file size has increased a lot from earlier for all the image files after this change. Not sure why this might happen.

Ref repo: https://github.com/FatehAK/memrise/tree/vsharp-test

**Comment by jw-12138** [comment]
I've also noticed this problem during test, that's why I added a layer that if the output image size is bigger than the input, the plugin will leave the image as is. seems like people are getting the same problem with sharp.js (https://github.com/lovell/sharp/issues/2213) as we are.

I think for now there is nothing I could do, sorry. 🥲

**Comment by FatehAK** [comment]
Damn thought so something's up with sharp.js. Cool thanks for taking the time to check 👍
